name: Generate resume
on:
  push:
    branches:
      - main
    paths:
      - 'resume.json'
jobs:
  generate_resume:
    name: Genereate resumes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Install deps
        run: npm i
      - name: Generate resumes
        run: npm run generate
      - name: Configure git
        run: |
          git config --global user.name 'Franky'
          git config --global user.email 'Franciscogonz64@users.noreply.github.com'
      - name: Commit resumes
        run: |
          git add -A
          git commit -m "regenerating resume"
          git push
