on:
  push:
    branches:
      - main
jobs:
  generate_resume:
    name: Buf tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
      - name: Generate resumes
        run: npm run generate
      - name: Commit resumes
        run: |
          git add -A
          git commit -m "regenerating commits"
          git push
